### ISSUE TITLE
MetaMask - RPC Error: execution reverted 

### ISSUE THREAD

**Issue by maxyang107** [33357/uniswap-v2-interface#1]
**Bug Description**
MetaMask - RPC Error: execution reverted 

**Steps to Reproduce**
Hello After deploying uniswap and replacing the contract, when the Ropsten testnet tries to add liquidity, applove is called normally, and an error is reported when Create Pool & Supply: "MetaMask - RPC Error: execution reverted ", what is the problem?
...

**Comment by 33357** [comment]
Make sure you deploy the contract correctly
